apiVersion: apps/v1
kind: Deployment
metadata:
    name: gs-mgmt
spec:
    replicas: 1
    selector:
        matchLabels:
            app: gs-mgmt
    strategy:
        type: Recreate
    template:
        metadata:
            labels:
                app: gs-mgmt
        spec:
            shareProcessNamespace: true
            initContainers:
            - name: prep-sysrepo
              image: docker.io/microsonic/gs-mgmt-debug:latest
              imagePullPolicy: IfNotPresent
              command: ['sysrepoctl', '-s', '/var/lib/goldstone/yang/gs', '--install', '/var/lib/goldstone/yang/gs/goldstone-tai.yang']
              volumeMounts:
              - name: shm
                mountPath: /dev/shm
              - name: sysrepo
                mountPath: /var/lib/sysrepo
            containers:
            - name: gscli
              image: docker.io/microsonic/gs-mgmt-debug:latest
              imagePullPolicy: IfNotPresent
              command: ['sh', '-c', 'sleep 15 && gscli -c "transponder; show"']
              volumeMounts:
              - name: shm
                mountPath: /dev/shm
              - name: sysrepo
                mountPath: /var/lib/sysrepo
            - name: gssouthd-tai
              image: docker.io/microsonic/gs-mgmt-debug:latest
              imagePullPolicy: IfNotPresent
              command: ['sh', '-c', 'sleep 10 && gssouthd-tai -v']
              volumeMounts:
              - name: shm
                mountPath: /dev/shm
              - name: sysrepo
                mountPath: /var/lib/sysrepo
            - name: taish-server
              image: docker.io/microsonic/tai:latest
              imagePullPolicy: IfNotPresent
              command: ['taish_server']
            volumes:
            - name: shm
              emptyDir:
                  medium: Memory
            - name: sysrepo
              emptyDir: {}
