apiVersion: v1
kind: ConfigMap
metadata:
    name: onl-platform
data:
    platform: "x86-64-kvm-x86-64-r0"

---

apiVersion: v1
kind: Service
metadata:
    name: netopeer2
spec:
    selector:
        app: gs-mgmt
    ports:
    - protocol: TCP
      port: 830

---

apiVersion: apps/v1
kind: Deployment
metadata:
    name: gs-mgmt
spec:
    replicas: 1
    selector:
        matchLabels:
            app: gs-mgmt
    strategy:
        type: Recreate
    template:
        metadata:
            labels:
                app: gs-mgmt
        spec:
            shareProcessNamespace: true
            initContainers:
            - name: prep-sysrepo
              image: docker.io/microsonic/gs-mgmt-debug:latest
              imagePullPolicy: IfNotPresent
              command: ['sysrepoctl', '-s', '/var/lib/goldstone/yang/gs', '--install', '/var/lib/goldstone/yang/gs/goldstone-tai.yang,/var/lib/goldstone/yang/gs/goldstone-onlp.yang']
              volumeMounts:
              - name: shm
                mountPath: /dev/shm
              - name: sysrepo
                mountPath: /var/lib/sysrepo
            - image: docker.io/microsonic/gs-mgmt-netopeer2:latest
              imagePullPolicy: IfNotPresent
              name: prep-np
              command: ['sh', '-c', '$NP2/setup.sh && $NP2/merge_hostkey.sh && $NP2/merge_config.sh']
              env:
              - name: NP2
                value: /usr/local/share/netopeer2/scripts
              - name: NP2_MODULE_OWNER
                value: root
              - name: NP2_MODULE_GROUP
                value: root
              - name: NP2_MODULE_PERMS
                value: "600"
              - name: NP2_MODULE_DIR
                value: /usr/local/share/yang/modules/netopeer2
              volumeMounts:
              - mountPath: /dev/shm
                name: shm
              - mountPath: /var/lib/sysrepo
                name: sysrepo
            containers:
            - name: cli
              image: docker.io/microsonic/gs-mgmt-debug:latest
              imagePullPolicy: IfNotPresent
              command: ['sh', '-c', 'while true; do gscli -c "transponder; show"; sleep 2; done']
              volumeMounts:
              - name: shm
                mountPath: /dev/shm
              - name: sysrepo
                mountPath: /var/lib/sysrepo
            - name: netopeer2
              image: docker.io/microsonic/gs-mgmt-netopeer2:latest
              imagePullPolicy: IfNotPresent
              command: ['netopeer2-server', '-d', '-v', '2']
              volumeMounts:
              - name: shm
                mountPath: /dev/shm
              - name: sysrepo
                mountPath: /var/lib/sysrepo
            - name: tai
              image: docker.io/microsonic/gs-mgmt-debug:latest
              imagePullPolicy: IfNotPresent
              command: ['sh', '-c', 'sleep 10 && gssouthd-tai -v']
              volumeMounts:
              - name: shm
                mountPath: /dev/shm
              - name: sysrepo
                mountPath: /var/lib/sysrepo
            - name: onlp
              image: docker.io/microsonic/gs-mgmt-debug:latest
              imagePullPolicy: IfNotPresent
              command: ['sh', '-c', 'ln -sf /lib/platform-config/x86-64-kvm-x86-64-r0/onl/lib/libonlp-x86-64-kvm-x86-64.so /lib/x86_64-linux-gnu/libonlp-platform.so.1 && gssouthd-onlp']
              volumeMounts:
              - name: shm
                mountPath: /dev/shm
              - name: sysrepo
                mountPath: /var/lib/sysrepo
              - name: onl-platform
                mountPath: /etc/onl/
              securityContext:
                capabilities:
                  add:
                  - IPC_OWNER
                  - IPC_LOCK
            - name: taish-server
              image: docker.io/microsonic/tai:latest
              imagePullPolicy: IfNotPresent
              command: ['taish_server']
            volumes:
            - name: shm
              emptyDir:
                  medium: Memory
            - name: sysrepo
              emptyDir: {}
            - name: onl-platform
              configMap:
                name: onl-platform
