on:
    pull_request:
        branches:
        - master
jobs:
    build:
        runs-on: ubuntu-latest
        steps:
        - uses: crazy-max/ghaction-docker-buildx@v1
        - uses: actions/checkout@v2
          with:
              submodules: true
        - run: make
